### ISSUE TITLE
Please add PS4 browser caching option.

### ISSUE THREAD

**Issue by eemcm2** [rareranger/ps4jbandroid#2]
Please add PS4 browser caching option.

**Comment by rareranger** [comment]
@eemcm2 What do you mean?

**Comment by eemcm2** [comment]
that the exploit is saved in the cache of the console browser, not having to use the app every time the console is turned on ...

**Comment by rareranger** [comment]
As far as I know the web browser on the PS4 doesn't cache any websites after the browser is closed. Only cookies and such. Nothing can be done about that.

**Comment by Yohoki** [comment]
Just FYI, PS4 browser IS able to cache websites.

I keep my ps4 offline 24/7, but the jailbreak websites (that have been cached) can open and run after closing the browser, or even shutting down the ps4 completely. Most of the jailbreaking websites cache automatically, and the PC self-host method also caches automatically. So, there's plenty of sources to check for how to implement it into this.

**Comment by rareranger** [comment]
> Just FYI, PS4 browser IS able to cache websites.
> 
> I keep my ps4 offline 24/7, but the jailbreak websites (that have been cached) can open and run after closing the browser, or even shutting down the ps4 completely. Most of the jailbreaking websites cache automatically, and the PC self-host method also caches automatically. So, there's plenty of sources to check for how to implement it into this.

Ah, I have the original base PS4 and the browser on there doesn't cache anything. Every website is re-loaded from its server on opening and fails to load while offline.

If the backend I'm using (NanoHTTPD) supports it I'll implement a response to the PS4 browser with the headers to enable caching, then someone can tell me if it works on their end after testing, since I can't test on my own console. 👍🏻

**Comment by eemcm2** [comment]
check the files of any host hosted on github, among the files there is one like cache.html or cachemanifest.html with that, the browser loads the exploit files in the cache.

https://github.com/Leeful/leeful.github.io/tree/master/9v4

**Comment by rareranger** [comment]
> check the files of any host hosted on github, among the files there is one like cache.html or cachemanifest.html with that, the browser loads the exploit files in the cache.
> 
> https://github.com/Leeful/leeful.github.io/tree/master/9v4

Ahh they're using an API (window.applicationCache) I didn't know about. Got some reading up and learning to do.

**Comment by Yohoki** [comment]
> Ah, I have the original base PS4 and the browser on there doesn't cache anything. Every website is re-loaded from its server on opening and fails to load while offline.
> 
> If the backend I'm using (NanoHTTPD) supports it I'll implement a response to the PS4 browser with the headers to enable caching, then someone can tell me if it works on their end after testing, since I can't test on my own console. 👍🏻

That's odd. Mine's the launch ps4 as well, so I'm not sure why yours doesn't cache at all. Have you tried using [Al-Azif's Exploit Host](https://github.com/Al-Azif/ps4-exploit-host)? It caches everything automatically so that the exploit (and even goldhen if it's setup right) autoloads even if you run it offline from a cold boot.

To be fair though, it's not REALLY a huge issue since 9.0 is so stable now. I haven't had to run the exploit in weeks. Check out [Kameleon's](https://github.com/KameleonReloaded/leeful900) host, based off of leeful900's site. It's what I've based my private site off of. It's got the caching function and autoloading for goldhen, so all you have to do is stick in the hacked USB and it does everything else.

Now if we could skip the USB step... That'd be awesome. XD

**Comment by rareranger** [comment]
> > Ah, I have the original base PS4 and the browser on there doesn't cache anything. Every website is re-loaded from its server on opening and fails to load while offline.
> > If the backend I'm using (NanoHTTPD) supports it I'll implement a response to the PS4 browser with the headers to enable caching, then someone can tell me if it works on their end after testing, since I can't test on my own console. 👍🏻
> 
> That's odd. Mine's the launch ps4 as well, so I'm not sure why yours doesn't cache at all. Have you tried using [Al-Azif's Exploit Host](https://github.com/Al-Azif/ps4-exploit-host)? It caches everything automatically so that the exploit (and even goldhen if it's setup right) autoloads even if you run it offline from a cold boot.

I was using https://cthugha.exploit.menu before self hosting and it didn't have caching enabled at the time. Seems to have just been added.

> 
> To be fair though, it's not REALLY a huge issue since 9.0 is so stable now. I haven't had to run the exploit in weeks. Check out [Kameleon's](https://github.com/KameleonReloaded/leeful900) host, based off of leeful900's site. It's what I've based my private site off of. It's got the caching function and autoloading for goldhen, so all you have to do is stick in the hacked USB and it does everything else.
> 
I'll be switching to leeful's host files instead of the ones I was using before. It would make it easier instead of starting from scratch because I'm lazy. :smile: 

> Now if we could skip the USB step... That's be awesome. XD
I know right. :smile:

**Comment by rareranger** [comment]
@Yohoki @eemcm2 I added the browser caching option. Uploading it now. Check https://github.com/rareranger/ps4jbandroid/releases/latest/ for version 2.2 in a few minutes. Cheers. :smile:
