### ISSUE TITLE
Unable to select payload

### ISSUE THREAD

**Issue by Johnyb62** [rareranger/ps4jbandroid#5]
Device: Samsung galaxy S21
When trying to add a payload (Payload> add paylpad>goldhen.bin) app continues to show 'no payloads added'.  Clicking send payload button confirms as states 'sending null paylpad to PS4'

**Comment by rareranger** [comment]
@Johnyb62 are you sure you are selecting a file from internal storage. Also make sure the file name ends with ".bin" all lowercase otherwise it won't get added.

Also why are you trying to add the GoldHen payload? It is loaded automatically from the server.

Also make sure you are on the latest version:  https://github.com/rareranger/ps4jbandroid/releases/latest/

**Comment by rareranger** [comment]
Found the issue. Fixed in version 3.3. Closed.

**Comment by Johnyb62** [comment]
Work great. Many thanks.
